[Interface]
# Bouncing = 2
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = off
PrivateKey = uJVS8oJw1YZ1LN2OiUWaQ7KTkjZ/TkYg8ODHYhmTNlA=
Address = 10.2.0.2/32, 2a07:b944::2:2/128
DNS = 10.2.0.1, 2a07:b944::2:1

[Peer]
# NL-FREE#33
PublicKey = 5+Pfgs2q2WVR1/E+wtAtHmts+wVaJCPcqXLEmO/tDD8=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 185.177.124.206:51820

# Uncomment the following line (delete the # symbol) to connect to Proton VPN using IPv6.
# Endpoint = [2a00:7c80:0:3bb::10]:51820
PersistentKeepalive = 25
